#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to Rose Pine
[colors.primary]
background = '#191724'
foreground = '#e0def4'

[colors.cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.vi_mode_cursor]
text = '#e0def4'
cursor = '#524f67'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#26233a'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.bright]
black = '#6e6a86'
red = '#eb6f92'
green = '#31748f'
yellow = '#f6c177'
blue = '#9ccfd8'
magenta = '#c4a7e7'
cyan = '#ebbcba'
white = '#e0def4'

[colors.hints]
start = {foreground = '#908caa', background = '#1f1d2e' }
end = { foreground = '#6e6a86', background = '#1f1d2e' }
