#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to Zenburn
[colors.primary]
background = '#3a3a3a'
foreground = '#dcdccc'

[colors.normal]
black = '#1e2320'
red = '#d78787'
green = '#60b48a'
yellow = '#dfaf8f'
blue = '#506070'
magenta = '#dc8cc3'
cyan = '#8cd0d3'
white = '#dcdccc'

[colors.bright]
black = '#709080'
red = '#dca3a3'
green = '#c3bf9f'
yellow = '#f0dfaf'
blue = '#94bff3'
magenta = '#ec93d3'
cyan = '#93e0e3'
white = '#ffffff'
