#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to Dracular+
[colors.primary]
background = '#212121'
foreground = '#f8f8f2'

[colors.cursor]
text = '#0e1415'
cursor = '#eceff4'

[colors.normal]
black = '#21222c'
red = '#ff5555'
green = '#50fa7b'
yellow = '#ffcb6b'
blue = '#82aaff'
magenta = '#c792ea'
cyan = '#8be9fd'
white = '#f8f9f2'

[colors.bright]
black = '#545454'
red = '#ff6e6e'
green = '#69ff94'
yellow = '#ffcb6b'
blue = '#d6acff'
magenta = '#ff92df'
cyan = '#a4ffff'
white = '#f8f8f2'
