#------------------------------------#
#----- Alacritty configurations -----#
#------------------------------------#

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 20000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to Moonfly
[colors.primary]
background = '#232326'
foreground = '#a7aab0'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
