[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[scrolling]
history = 100000
multiplier = 2

[cursor]
style = {shape = "Block", blinking = "Always"}
blink_interval = 650

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
blur = false
option_as_alt = "both"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 5
y = 5

[window.position]
x = 0
y = 0

# Thanks to Base16 Default Dark
[colors.primary]
background = '#141414'
foreground = '#d8d8d8'

[colors.cursor]
text = '#141414'
cursor = '#d8d8d8'

[colors.normal]
black = '#141414'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#d8d8d8'

[colors.bright]
black = '#585858'
red = '#ab4642'
green = '#a1b56c'
yellow = '#f7ca88'
blue = '#7cafc2'
magenta = '#ba8baf'
cyan = '#86c1b9'
white = '#f8f8f8'
